version: '3'

services:
  nginx:
    build:
      context: ./docker/development/nginx
    volumes:
      - ./:/app
    container_name: ${APP_NAME}-nginx
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - php-fpm

  php-fpm:
    build:
      context: ./docker/development/php-fpm
    volumes:
      - ./:/app
      - ./var/cache:/app/var/cache
    container_name: ${APP_NAME}-php-fpm
    depends_on:
      - database
    tty: true

  php-cli:
    build:
      context: ./docker/development/php-cli
    volumes:
      - ./:/app
    container_name: ${APP_NAME}-php-cli

###> doctrine/doctrine-bundle ###
  database:
    image: postgres:${POSTGRES_VERSION}-alpine
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    volumes:
      - db-data:/var/lib/postgresql/data:rw
    ports:
      - "54321:5432"
    container_name: ${APP_NAME}-postgres
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
      # - ./init.sql:/docker-entrypoint-initdb.d/init.sql
###< doctrine/doctrine-bundle ###

volumes:
###> doctrine/doctrine-bundle ###
  db-data:
###< doctrine/doctrine-bundle ###
